### ISSUE TITLE
Unknown OS

### ISSUE THREAD

**Issue by alexmigf** [juju/utils#224]
Hi,

I'm facing an error after installed juju, says unknown OS. I'm running GalliumOs (Xubuntu 15.04).

```
$ juju --version
panic: osVersion reported an error: unknown OS for series: "unknown"

goroutine 16 [running]:
runtime.panic(0x1693540, 0xc2080935e0)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/juju/juju/version.MustOSFromSeries(0x214bbd0, 0x7, 0x1)
	/build/juju-core-Fp5GnP/juju-core-1.25.0/src/github.com/juju/juju/version/osversion.go:36 +0xda
github.com/juju/juju/version.init()
	/build/juju-core-Fp5GnP/juju-core-1.25.0/src/github.com/juju/juju/version/version.go:45 +0x5d3
github.com/juju/juju/provider/vsphere.init()
	/build/juju-core-Fp5GnP/juju-core-1.25.0/src/github.com/juju/juju/provider/vsphere/userdata.go:23 +0x59
github.com/juju/juju/provider/all.init()
	/build/juju-core-Fp5GnP/juju-core-1.25.0/src/github.com/juju/juju/provider/all/all.go:18 +0x46
main.init()
	/build/juju-core-Fp5GnP/juju-core-1.25.0/src/github.com/juju/juju/cmd/juju/main.go:22 +0x4b

goroutine 19 [finalizer wait]:
runtime.park(0x412ff0, 0x3310430, 0x330c509)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x3310430, 0x330c509)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445
```

**Comment by anastasiamac** [comment]
Thank you for the issue, @alexmigf!

We track our issues on launchpad and related bug is filed here - https://bugs.launchpad.net/juju/+bug/1616531

Feel free to add your voting to it \o/
